version: "3.9"
services:
  web:
    build:
      context: .               # build from the repo root
      dockerfile: Dockerfile
      args:
        # point to your NEW subfolder that contains package.json
        # EXAMPLES:
        # APP_DIR: "silveroak-connect-main/ui"
        # APP_DIR: "silveroak-connect-main/frontend"
        APP_DIR: "silveroak-connect-main"   # <-- CHANGE THIS to your actual new path
    image: silveroak-connect:latest
    container_name: silveroak-connect
    ports:
      - "8080:80"
    restart: always
